#!/usr/bin/env ruby
# frozen_string_literal: true
#
# SPDX-License-Identifier: MIT
# scripts/knowledge.rb
#
# Query surface over `docs/knowledge/`. The corpus is one bullet per entry
# across dozens of topic files; without a filter, answering "what do we already
# know about RETRY-12" means reading a 20 KB file. This turns that into a query
# that returns the handful of entries which actually cite the requirement.
#
# Two trees, one query surface:
#   harvested/  generated by `knowledge-harvest`, never hand-edited. A `<sub>`
#               sha there digests the WHOLE source file, so a hand edit inside
#               an entry is invisible to the next harvest -- it is regenerated
#               or duplicated. Hence: no hand edits, ever.
#   notes/      hand-written during implementation. Role `review`, a manual
#               `sha:` marker. What the implementation found, which outranks
#               what the documents say.
#
# `verify_knowledge_structure.rb` is the gate that keeps the two apart. This
# file is not a gate: `--coverage` and `--gaps` are reports you run by hand.
#
# Ruby >= 3.2, standard library only. Ported from the Node SDK's
# `scripts/knowledge.mjs`.

require "digest"
require "json"
require "optparse"
require "set"

module Knowledge
  # `INDEX.md` is a generated topic table, `SOURCES.md` a provenance manifest
  # and `README.md` the two-tree contract; none holds entries, and all would
  # parse as noise.
  NON_TOPIC_FILES = ["INDEX.md", "SOURCES.md", "README.md"].freeze

  # Appendix B is the conformance-test checklist. Its entries roll several
  # requirement IDs into one "the suite verifies X, Y, Z" sentence, so they make
  # an ID look cited while carrying none of its content. A large share of cited
  # IDs resolve ONLY to a roll-up -- a silent wrong answer unless called out.
  ROLLUP_SOURCE = "appendix-b-conformance-test-checklist"

  # Provenance roles the corpus uses, most common first. `review` is the notes
  # tree's role and appears nowhere under `harvested/`.
  ROLES = ["spec", "design", "styleguide", "review"].freeze
  HARVESTED_ROLES = (ROLES - ["review"]).freeze

  # The two trees, and the value of an entry's `origin` field for each.
  ORIGINS = ["harvested", "note"].freeze

  # The six section names the parser recognises, in emission order. No file
  # carries all six: `Superseded` exists only under `notes/`, where an override
  # is recorded -- `verify_knowledge_structure.rb` rejects one under
  # `harvested/`.
  SECTIONS = ["Rules", "Constraints", "Conclusions", "Reference", "Conflicts", "Superseded"].freeze

  # A usage error: a typo in a flag value, a table whose format changed. Exit 2,
  # because a silent empty result is worse than a refusal.
  class UsageError < StandardError; end

  # The corpus or the requirement index is simply not there. Exit 1: nothing is
  # wrong with the command, this checkout has not been harvested yet.
  class NotHarvested < StandardError; end

  # Where everything lives, relative to one root. `--root` exists so the CLI can
  # be pointed at another checkout (a sibling SDK's populated corpus) for a
  # comparison run, and so the tests can run against a fixture tree.
  class Paths
    ENV_ROOT = "KNOWLEDGE_ROOT"

    attr_reader :root

    def initialize(root)
      @root = File.expand_path(root.to_s)
    end

    # The repository root is the parent of `scripts/`, so the CLI works from any
    # working directory.
    def self.default
      new(ENV[ENV_ROOT] || File.expand_path("..", __dir__))
    end

    def knowledge_dir = File.join(root, "docs", "knowledge")
    def harvested_dir = File.join(knowledge_dir, "harvested")
    def notes_dir = File.join(knowledge_dir, "notes")
    def sources_manifest = File.join(harvested_dir, "SOURCES.md")
    def topic_index = File.join(harvested_dir, "INDEX.md")
    def product_spec_dir = File.join(root, "docs", "product-spec")
    def work_dir = File.join(root, "docs", "work")

    def appendix_c
      File.join(product_spec_dir, "appendix-c-consolidated-normative-requirement-index.md")
    end

    # An absolute source path (the styleguide is a sibling repository) is used as
    # given; everything else is repo-relative.
    def resolve(source)
      source.start_with?("/") ? source : File.join(root, source)
    end

    def relative(path)
      path.delete_prefix("#{root}/")
    end
  end

  # Requirement-ID arithmetic. A bare `\b[A-Z]{2,12}-\d+\b` is not a
  # requirement-ID matcher: it also claims `UTF-8`, `SHA-256`, `ISO-8601` and
  # `RFC-3986`. The only authority on what a requirement ID looks like is
  # appendix C, so every function here takes the derived prefix allowlist.
  module Ids
    TOKEN = /\b[A-Z][A-Z0-9]{1,11}-\d+\b/

    module_function

    def prefix_of(id)
      id[0...id.rindex("-")]
    end

    def number_of(id)
      id[(id.rindex("-") + 1)..].to_i
    end

    # Tokenize, then compare whole tokens. Never substring-match: `HTTP-7` and
    # `HTTP-70` are different requirements and a substring test conflates them.
    def extract(text, prefixes)
      found = []
      text.scan(TOKEN) do |token|
        next unless prefixes.include?(prefix_of(token))
        found << token unless found.include?(token)
      end
      found
    end

    def compare(left, right)
      if prefix_of(left) == prefix_of(right)
        number_of(left) <=> number_of(right)
      else
        prefix_of(left) <=> prefix_of(right)
      end
    end

    def sort(ids)
      ids.sort { |left, right| compare(left, right) }
    end

    # `RETRY-1..45 RETRY-47` rather than 46 tokens. A phase checklist cites its
    # whole family, and printing every ID three times over is most of the output.
    def compress(ids)
      runs = []
      sort(ids).each do |id|
        last = runs.last
        if last && prefix_of(last.first) == prefix_of(id) && number_of(last.last) + 1 == number_of(id)
          last << id
        else
          runs << [id]
        end
      end
      runs.map { |run| run.size < 3 ? run.join(" ") : "#{run.first}..#{number_of(run.last)}" }.join(" ")
    end
  end

  Requirement = Struct.new(:id, :level, :subsystem)

  # Appendix C is the canonical requirement index and the only authority on what
  # a requirement ID looks like. The prefix allowlist is derived from it at
  # runtime and never hardcoded, so a spec revision that adds a subsystem is
  # picked up without editing this file -- and so is the prefix -> subsystem
  # routing that used to be a hand-maintained table in the skill.
  class AppendixC
    ROW = /\A\|\s*([A-Z][A-Z0-9]{1,11}-\d+)\s*\|/
    # A chapter must share at least half its name with the subsystem cell before
    # it is offered as that prefix's chapter; below that it is a coincidence.
    CHAPTER_MATCH_FLOOR = 0.5

    attr_reader :requirements, :path

    def self.load(paths)
      path = paths.appendix_c
      text = begin
        File.read(path, encoding: "UTF-8")
      rescue Errno::ENOENT
        raise NotHarvested, <<~MESSAGE.strip
          cannot read the canonical requirement index at #{path}
          The requirement-ID allowlist is derived from that table at runtime and there is no
          fallback — a bare regex would claim UTF-8, SHA-256 and RFC-3986 as requirement IDs.
          Point this at a checkout that has it with --root DIR (or set #{Paths::ENV_ROOT}).
        MESSAGE
      end
      new(parse(text, path), paths)
    end

    def self.parse(text, path)
      requirements = {}
      text.each_line do |line|
        match = ROW.match(line)
        next unless match

        cells = line.split("|").map(&:strip)
        # `| ID | Level | Subsystem | Requirement |` -- leading/trailing empties.
        requirements[match[1]] = Requirement.new(match[1], cells[2].to_s, cells[3].to_s)
      end
      if requirements.empty?
        raise UsageError, "parsed zero requirement IDs out of #{path}; its table format changed " \
                          "and the allowlist cannot be derived — refusing to fall back to a bare " \
                          "regex, which false-positives on UTF-8 and SHA-256"
      end
      requirements
    end

    def initialize(requirements, paths)
      @requirements = requirements
      @paths = paths
    end

    def ids = @requirements.keys
    def size = @requirements.size
    def key?(id) = @requirements.key?(id)
    def [](id) = @requirements[id]

    def prefixes
      @prefixes ||= @requirements.each_key.map { |id| Ids.prefix_of(id) }.to_set
    end

    def ids_for(prefix)
      Ids.sort(@requirements.each_key.select { |id| Ids.prefix_of(id) == prefix })
    end

    # The subsystem cell, taken as the most common value across the family: one
    # stray row must not rename the subsystem.
    def subsystem_for(prefix)
      counts = Hash.new(0)
      ids_for(prefix).each { |id| counts[@requirements[id].subsystem] += 1 }
      counts.max_by { |_, count| count }&.first.to_s
    end

    def levels_for(prefix)
      counts = Hash.new(0)
      ids_for(prefix).each { |id| counts[@requirements[id].level] += 1 }
      counts.sort_by { |_, count| -count }.to_h
    end

    # The owning chapter, derived by matching the subsystem cell against the
    # numbered chapter files rather than from a routing table that drifts.
    def chapter_for(prefix)
      wanted = name_tokens(subsystem_for(prefix))
      return nil if wanted.empty?

      best = nil
      chapter_files.each do |file|
        tokens = name_tokens(file.sub(/\A\d+-/, "").sub(/\.md\z/, ""))
        next if tokens.empty?

        score = (tokens & wanted).size.fdiv(tokens.size)
        next if score < CHAPTER_MATCH_FLOOR

        best = [score, file] if best.nil? || score > best.first
      end
      best&.last
    end

    def chapter_files
      @chapter_files ||= if Dir.exist?(@paths.product_spec_dir)
                           Dir.children(@paths.product_spec_dir).grep(/\A\d{2}-.*\.md\z/).sort
                         else
                           []
                         end
    end

    private

    # Lower-cased word tokens with a naive singular fold, so `seams` matches
    # `seam` and `pipelines` matches `pipeline`.
    def name_tokens(text)
      text.downcase.scan(/[a-z0-9]+/).map { |word| word.sub(/s\z/, "") }.uniq
    end
  end

  # One `<sub>` provenance line, parsed. Two shapes are in the corpus:
  #   role · `path:lines` · confidence · sha:xxxx        (the common one)
  #   roleA `pathA` · roleB `pathB` · resolution-status  (Conflicts entries)
  # so role and path are sometimes separate ` · ` fields and sometimes one. Walk
  # the fields and classify each rather than reading them positionally.
  class SubLine
    FIELD_SEPARATOR = " · "
    ROLE_AND_SOURCE = /\A(\S+)\s+`(.+)`\z/
    BARE_SOURCE = /\A`(.+)`\z/

    Parsed = Struct.new(:roles, :sources, :confidence, :sha)

    def self.parse(inner)
      roles = []
      sources = []
      confidence = nil
      sha = nil
      pending_role = nil

      inner.split(FIELD_SEPARATOR).each do |raw|
        field = raw.strip

        if (pair = ROLE_AND_SOURCE.match(field))
          roles << pair[1]
          sources << pair[2]
          pending_role = nil
          next
        end

        if (bare = BARE_SOURCE.match(field))
          roles << (pending_role || "unknown")
          sources << bare[1]
          pending_role = nil
          next
        end

        if field.start_with?("sha:")
          sha = field.delete_prefix("sha:")
          next
        end

        # A lone word that is not a confidence level is the role of the source
        # field that follows it; anything else is the confidence / status.
        confidence = pending_role unless pending_role.nil?
        pending_role = /\A\S+\z/.match?(field) ? field : nil
        confidence = field if pending_role.nil?
      end
      confidence = pending_role unless pending_role.nil?

      Parsed.new(roles, sources, confidence, sha)
    end
  end

  # One entry: a bullet, its provenance line, and everything derived from them.
  class Entry
    # Styleguide `<sub>` paths carry a numbered chapter file
    # (`.../ruby/06-classes-and-data-modeling.md:168-183`), so "styleguide 6.7"
    # is answerable by matching the chapter number -- no hardcoded chapter ->
    # topic table that could drift from the styleguide itself. Only
    # styleguide-role sources count: `docs/product-spec/04-....md` is a numbered
    # chapter too, and conflating the two would answer "styleguide 4" with spec
    # chapter 4. `roles[i]` pairs with `sources[i]`.
    STYLEGUIDE_CHAPTER = %r{/(\d{2})-[^/]*\.md(?::|\z)}

    attr_reader :file, :topic, :origin, :line, :section, :roles, :sources, :overridden_by, :overrides
    attr_accessor :text, :key, :reqs, :confidence, :sha, :sub_line

    def initialize(file:, topic:, origin:, line:, section:, text:)
      @file = file
      @topic = topic
      @origin = origin
      @line = line
      @section = section
      @text = text
      @key = nil
      @reqs = []
      @roles = []
      @sources = []
      @confidence = nil
      @sha = nil
      @sub_line = nil
      @overridden_by = []
      @overrides = []
    end

    def role = @roles.first
    def source = @sources.first
    def note? = @origin == "note"

    # One bullet carrying two `<sub>` lines is malformed, but overwriting the
    # first with the second drops its sources -- and a source is what the
    # structural gate checks, so the malformed half would escape the check.
    # Accumulate instead, and let the gate see everything the entry cites.
    def merge_sub(parsed, raw_line)
      if @sub_line.nil?
        @roles.concat(parsed.roles)
        @sources.concat(parsed.sources)
        @confidence = parsed.confidence
        @sha = parsed.sha
        @sub_line = raw_line
      else
        @roles.concat(parsed.roles)
        @sources.concat(parsed.sources)
        @sub_line = "#{@sub_line} #{raw_line}"
      end
    end

    # `pagination.md` exists in both trees, so a bare basename is ambiguous. A
    # harvested entry prints as `pagination.md:134`, a note as
    # `notes/pagination.md:5`.
    def location
      "#{note? ? "notes/" : ""}#{@file}:#{@line}"
    end

    # True when every source this entry cites is the conformance checklist, i.e.
    # the entry names requirement IDs without saying anything about them.
    def rollup?
      !@sources.empty? && @sources.all? { |source| source.include?(ROLLUP_SOURCE) }
    end

    def chapters
      found = []
      @sources.each_with_index do |source, index|
        next unless @roles[index] == "styleguide"

        match = STYLEGUIDE_CHAPTER.match(source)
        found << match[1].to_i.to_s if match
      end
      found
    end

    # Source paths with any `:12-18` line suffix removed -- what the drift check
    # and the structural gate both hash and resolve.
    def source_paths
      @sources.map { |source| source.sub(/:[\d,\-]+\z/, "") }
    end

    def to_h
      {
        file: @file, topic: @topic, origin: @origin, key: @key, line: @line,
        section: @section, text: @text, role: role, roles: @roles,
        source: source, sources: @sources, confidence: @confidence, sha: @sha,
        sub_line: @sub_line, reqs: @reqs, rollup: rollup?,
        overridden_by: @overridden_by, overrides: @overrides,
      }
    end
  end

  # Turns one topic file into entries.
  class TopicParser
    SECTION_HEADING = /\A\#\#\s+(.+?)\s*\z/
    BULLET_START = /\A-\s+(.*)\z/
    SUB_LINE = %r{\A\s+<sub>(.*)</sub>\s*\z}

    def initialize(prefixes)
      @prefixes = prefixes
    end

    def parse(path, origin)
      lines = self.class.read_lines(path)
      file = File.basename(path)
      topic = file.sub(/\.md\z/, "")
      entries = []
      section = nil
      current = nil

      flush = lambda do
        next if current.nil?

        current.reqs = Ids.extract(current.text, @prefixes)
        current.key = self.class.entry_key(topic, current.text)
        entries << current
        current = nil
      end

      lines.each_with_index do |line, index|
        if (heading = SECTION_HEADING.match(line))
          flush.call
          section = heading[1]
          next
        end

        if current && (sub = SUB_LINE.match(line))
          current.merge_sub(SubLine.parse(sub[1]), line.strip)
          next
        end

        if (bullet = BULLET_START.match(line))
          flush.call
          current = Entry.new(file: file, topic: topic, origin: origin,
                              line: index + 1, section: section, text: bullet[1])
          next
        end

        # A continuation line: any non-`<sub>` line before the open bullet's
        # provenance line -- a few Conflicts entries run to several paragraphs,
        # and dropping the tail silently loses the requirement IDs it cites. An
        # entry therefore ends only at its `<sub>`, at the next bullet, at the
        # next heading, or at end of file.
        current.text = "#{current.text} #{line.strip}" if current && current.sub_line.nil? && !line.strip.empty?
      end

      flush.call
      entries
    end

    # A topic file authored on Windows, or saved with a BOM, is the one input
    # that fails silently rather than loudly: `\r` defeats BULLET_START's anchor
    # and a BOM defeats SECTION_HEADING, so the file parses to zero entries and
    # every downstream gate then reports OK over a hole. Normalize both at the
    # door.
    def self.read_lines(path)
      text = File.read(path, encoding: "UTF-8")
      text.sub(/\A﻿/, "").split(/\r?\n/, -1)
    rescue Errno::ENOENT
      raise UsageError, "cannot read the topic file #{path}"
    end

    # A citable name for one entry, stable across a re-order and a re-harvest.
    # The line number is not that name: an entry moves whenever a neighbour is
    # added. The `<sub>` sha is not either -- it digests the whole source file,
    # so every entry harvested from one file shares it. The digest of the
    # entry's own text changes when, and only when, the rule changes, which is
    # what a note naming a broken rule wants: a changed rule needs a fresh check.
    def self.entry_key(topic, text)
      "#{topic}/#{Digest::SHA256.hexdigest(text.rstrip)[0, 8]}"
    end
  end

  # Both trees, loaded and cross-linked.
  class Corpus
    # A key inside an entry's prose, backticked: `pagination/81881061`.
    CITED_KEY = %r{`([a-z0-9-]+/[0-9a-f]{8})`}

    attr_reader :entries

    def self.load(paths, prefixes)
      unless Dir.exist?(paths.knowledge_dir)
        raise NotHarvested, <<~MESSAGE.strip
          #{paths.relative(paths.knowledge_dir)} does not exist under #{paths.root}
          The corpus is two trees — harvested/ (what the source documents say, written by the
          knowledge-harvest skill) and notes/ (what the implementation found) — and neither has
          been created here yet. Harvest first, or query another checkout with --root DIR.
        MESSAGE
      end
      unless Dir.exist?(paths.harvested_dir)
        raise NotHarvested, "cannot read the harvested corpus at #{paths.harvested_dir}; " \
                            "docs/knowledge/ is two trees (harvested/ and notes/) and the " \
                            "harvested one is not optional"
      end

      parser = TopicParser.new(prefixes)
      entries = topic_files(paths).flat_map { |topic| parser.parse(topic[:path], topic[:origin]) }
      new(entries)
    end

    # Every topic file in both trees, harvested first, as records rather than
    # bare names: a caller needs the tree an entry came from, and `pagination.md`
    # exists in both.
    def self.topic_files(paths)
      trees = [["harvested", paths.harvested_dir], ["note", paths.notes_dir]]
      trees.flat_map do |origin, dir|
        # The notes tree holds a file only where a note exists. None yet is a
        # legitimate state, not a broken checkout.
        next [] unless Dir.exist?(dir)

        names = Dir.children(dir).select { |name| name.end_with?(".md") && !NON_TOPIC_FILES.include?(name) }
        names.sort.map do |name|
          {file: name, topic: name.sub(/\.md\z/, ""), path: File.join(dir, name), origin: origin}
        end
      end
    end

    def initialize(entries)
      @entries = entries
      link_overrides
    end

    def empty? = @entries.empty?

    def topics
      @entries.map(&:topic).uniq.sort
    end

    def citation_index
      @citation_index ||= begin
        index = {}
        @entries.each do |entry|
          entry.reqs.each { |id| (index[id] ||= []) << entry }
        end
        index
      end
    end

    # `overridden_by` is also how a stale reference becomes visible. A key
    # digests entry text, so a re-harvest that rewords a rule leaves the citing
    # note pointing at nothing; this is that list, and `--key` reports it.
    def dangling_keys
      known = @entries.map(&:key).to_set
      dangling = []
      @entries.each do |note|
        next unless note.note?

        note.text.scan(CITED_KEY) do |(cited)|
          dangling << {note: note.location, cited: cited} unless known.include?(cited)
        end
      end
      dangling
    end

    private

    # A note names the harvested rule it overrides by that rule's key. Resolve
    # those references once, at load, and hang the answer on both ends.
    #
    # Without this the override is prose inside one note and nothing else: a
    # query that lands on the harvested entry -- by `--section reference`, by a
    # bare word, by anything that does not also return the note -- hands back a
    # rule the implementation has already overruled, with no sign that it did.
    def link_overrides
      by_key = @entries.to_h { |entry| [entry.key, entry] }
      @entries.each do |note|
        next unless note.note?

        note.text.scan(CITED_KEY) do |(cited)|
          target = by_key[cited]
          next if target.nil? || target.equal?(note)

          target.overridden_by << note.location
          note.overrides << cited
        end
      end
    end
  end

  # `harvested/SOURCES.md`: every source the corpus was derived from, with the
  # sha256 of the whole file at harvest time.
  class SourceManifest
    # `| \`path\` | role | \`sha\` | date |` -- the sha cell sometimes carries an
    # annotation after the digest, so take the first backticked token in it.
    ROW = /\A\|\s*`([^`]+)`\s*\|\s*([^|]*?)\s*\|\s*`([0-9a-f]+)`/
    # Any data row of the manifest table, parseable or not. Counting these is
    # what turns "47 sources OK" from a count of rows that happened to match into
    # a statement about the table.
    ANY_ROW = /\A\|\s*`([^`]+)`\s*\|/
    # A digest short enough to collide by accident is not a pin.
    MIN_SHA_LENGTH = 12

    Row = Struct.new(:path, :role, :sha)

    attr_reader :rows, :path

    def self.exist?(paths) = File.file?(paths.sources_manifest)

    def self.load(paths)
      path = paths.sources_manifest
      begin
        new(parse(File.read(path, encoding: "UTF-8"), path), path)
      rescue Errno::ENOENT
        raise NotHarvested, "cannot read the harvest manifest at #{path}; it is written by the " \
                            "knowledge-harvest skill alongside harvested/"
      end
    end

    def self.parse(text, path)
      rows = []
      listed = 0
      text.each_line do |line|
        next unless ANY_ROW.match?(line)

        listed += 1
        match = ROW.match(line)
        rows << Row.new(match[1], match[2], match[3]) if match
      end

      raise UsageError, "parsed zero source rows out of #{path}; its table format changed" if rows.empty?

      if rows.size < listed
        raise UsageError, "#{path} lists #{listed} sources but only #{rows.size} parse; the rest " \
                          "carry a malformed digest cell and would be silently skipped"
      end
      rows.each do |row|
        next if row.sha.length >= MIN_SHA_LENGTH

        raise UsageError, "#{row.path} is pinned to a #{row.sha.length}-character digest; at " \
                          "least #{MIN_SHA_LENGTH} are needed for the comparison to mean anything"
      end
      rows
    end

    def initialize(rows, path)
      @rows = rows
      @path = path
      @by_path = rows.to_h { |row| [row.path, row] }
    end

    def sha_for(source_path) = @by_path[source_path]&.sha

    # The directories the manifest itself names -- the allowlist of source roots
    # the structural gate checks harvested citations against.
    def roots
      @rows.map { |row| File.dirname(row.path) }.uniq.sort
    end
  end

  # A query that touches an entry whose source has changed since the harvest is
  # answering from a stale document. That is a warning, never a failure: drift is
  # normal, and the fix (a re-harvest) is a user-invoked skill.
  class DriftCheck
    def initialize(manifest, paths)
      @manifest = manifest
      @paths = paths
      @digests = {}
    end

    # nil when there is no manifest to check against, so the caller stays simple.
    def self.for(paths)
      SourceManifest.exist?(paths) ? new(SourceManifest.load(paths), paths) : nil
    rescue UsageError, NotHarvested
      nil
    end

    # One line per distinct stale source, however many entries derive from it:
    # each source file is hashed at most once per run.
    def warnings_for(entries)
      counts = Hash.new(0)
      entries.each do |entry|
        entry.source_paths.each { |source| counts[source] += 1 if @manifest.sha_for(source) }
      end

      counts.sort.filter_map do |source, count|
        recorded = @manifest.sha_for(source)
        actual = digest_of(source, recorded.length)
        next if actual.nil? || actual == recorded

        "warning: stale #{source} — harvested at sha #{recorded}, now #{actual}; " \
          "#{count} of these entries derive from it. Re-harvest it, or read the file."
      end
    end

    private

    # A missing file is not drift: the styleguide root is a sibling repository at
    # an absolute path and is legitimately absent off the harvest machine.
    def digest_of(source, width)
      @digests.fetch(source) do
        @digests[source] = begin
          Digest::SHA256.file(@paths.resolve(source)).hexdigest[0, width]
        rescue SystemCallError
          nil
        end
      end
    end
  end

  # The filters, and the one predicate that applies them. Different filters AND
  # together; multiple values inside one filter OR.
  class Query
    DIMENSIONS = %i[reqs keys prefixes origins topics roles chapters sections patterns].freeze
    # A key is `<topic>/<8 hex>`. Not validated against the corpus: a key that
    # resolves to nothing is exactly what a reader needs told.
    ENTRY_KEY = %r{\A[a-z0-9-]+/[0-9a-f]{8}\z}

    attr_reader :reqs, :keys, :prefixes, :origins, :topics, :roles, :chapters, :sections, :patterns

    def initialize(reqs: [], keys: [], prefixes: [], origins: [], topics: [],
                   roles: [], chapters: [], sections: [], patterns: [])
      @reqs = reqs
      @keys = keys
      @prefixes = prefixes
      @origins = origins
      @topics = topics
      @roles = roles
      @chapters = chapters
      @sections = sections
      @patterns = patterns
    end

    def self.build(options, words, appendix, extra_reqs: [], warn: $stderr)
      reqs = (split_values(options[:req], "--req") + extra_reqs).uniq
      reqs.each do |id|
        next if appendix.key?(id)

        warn.puts("warning: #{id} is not in appendix C — it is not a canonical requirement ID, " \
                  "so no entry can legitimately cite it")
      end

      new(
        reqs: reqs,
        keys: parse_keys(options),
        prefixes: parse_id_prefixes(options, appendix.prefixes),
        origins: parse_enum(options[:origin], "--origin", ORIGINS),
        topics: split_values(options[:topic], "--topic"),
        roles: parse_enum(options[:role], "--role", ROLES),
        chapters: parse_chapters(options, warn),
        sections: parse_sections(options),
        patterns: parse_patterns(options, words),
      )
    end

    # `--req A,B --req C` and `--req A --req B` mean the same thing: values
    # inside one filter OR.
    #
    # An empty value is dropped, and a filter whose values were ALL empty is a
    # refusal. `--topic ''` and the one-character typo `--topic 'a,b,'` would
    # otherwise match every file, so a stray comma in the skill's own
    # comma-separated audit form silently turns a 55-entry query into the whole
    # corpus -- the one thing this tool exists to prevent.
    def self.split_values(values, flag)
      supplied = Array(values).flat_map { |value| value.empty? ? [value] : value.split(",", -1) }
      kept = supplied.reject { |value| value.strip.empty? }
      if !supplied.empty? && kept.empty?
        raise UsageError, "#{flag} was given only empty values; an empty value matches every " \
                          "entry, so this would print the whole corpus. Drop the flag, or a " \
                          "stray comma."
      end
      kept
    end

    def self.parse_enum(values, flag, allowed)
      split_values(values, flag).map do |value|
        resolved = allowed.find { |name| name == value }
        raise UsageError, "unknown #{flag.delete_prefix("--")} '#{value}'; the values are #{allowed.join(", ")}" unless resolved

        resolved
      end
    end

    def self.parse_sections(options)
      split_values(options[:section], "--section").map do |value|
        resolved = SECTIONS.find { |name| name.casecmp?(value) }
        raise UsageError, "unknown section '#{value}'; the six sections are #{SECTIONS.join(", ")}" unless resolved

        resolved
      end
    end

    # An ID family, for the audit query: `--prefix HTTP` is every HTTP-N entry,
    # which `--req` cannot express without listing all of them. Validated against
    # appendix C for the same reason `--req` warns -- `--prefix UTF` would
    # otherwise be a silent empty result rather than a typo.
    def self.parse_id_prefixes(options, known)
      split_values(options[:prefix], "--prefix").map do |value|
        prefix = value.strip.upcase
        unless known.include?(prefix)
          raise UsageError, "'#{prefix}' is not a requirement-ID prefix in appendix C, so no " \
                            "entry can legitimately cite one. The prefixes are " \
                            "#{known.to_a.sort.join(" ")}"
        end
        prefix
      end
    end

    def self.parse_keys(options)
      split_values(options[:key], "--key").map do |value|
        key = value.strip
        unless ENTRY_KEY.match?(key)
          raise UsageError, "'#{key}' is not an entry key; a key is <topic>/<8 hex>, as printed " \
                            "after the section name on every result"
        end
        key
      end
    end

    # "styleguide 6.7" -- the chapter is queryable, the sub-section number is
    # not, so take the chapter and say plainly that the rest was dropped.
    def self.parse_chapters(options, warn)
      split_values(options[:chapter], "--chapter").map do |value|
        match = /\A(\d{1,2})(?:\.(\d+))?\z/.match(value.strip)
        raise UsageError, "unknown chapter '#{value}'; expected a styleguide chapter like 6 or 6.7" unless match

        unless match[2].nil?
          warn.puts("note: entries record a chapter file and line range, not section numbers — " \
                    "querying chapter #{match[1]}, ignoring .#{match[2]}. Narrow with bare words.")
        end
        match[1].to_i.to_s
      end
    end

    # An empty pattern matches every entry, exactly as an empty `--topic` does,
    # so it gets the same refusal rather than printing the corpus.
    def self.parse_patterns(options, words)
      supplied = Array(options[:grep]) + words
      if !supplied.empty? && supplied.all? { |value| value.strip.empty? }
        raise UsageError, "--grep was given only empty values; an empty pattern matches every " \
                          "entry, so this would print the whole corpus."
      end

      patterns = []
      Array(options[:grep]).each do |source|
        next if source.strip.empty?

        begin
          patterns << Regexp.new(source, Regexp::IGNORECASE)
        rescue RegexpError => error
          raise UsageError, "--grep '#{source}' is not a valid regex: #{error.message}"
        end
      end
      words.each do |word|
        patterns << Regexp.new(Regexp.escape(word), Regexp::IGNORECASE) unless word.strip.empty?
      end
      patterns
    end

    def values_for(dimension)
      case dimension
      when :reqs then @reqs
      when :keys then @keys
      when :prefixes then @prefixes
      when :origins then @origins
      when :topics then @topics
      when :roles then @roles
      when :chapters then @chapters
      when :sections then @sections
      when :patterns then @patterns
      else raise ArgumentError, "unknown filter dimension #{dimension}"
      end
    end

    def used_dimensions
      DIMENSIONS.select { |name| !values_for(name).empty? }
    end

    def empty? = used_dimensions.empty?

    # One dimension on its own, for the zero-result diagnosis: only a filter that
    # matches nothing by itself gets to explain the empty result.
    def solo(dimension)
      Query.new(**{dimension => values_for(dimension)})
    end

    def match?(entry)
      return false unless @keys.empty? || @keys.include?(entry.key)
      return false unless @reqs.empty? || @reqs.any? { |id| entry.reqs.include?(id) }
      return false unless @prefixes.empty? || entry.reqs.any? { |id| @prefixes.include?(Ids.prefix_of(id)) }
      return false unless @topics.empty? || @topics.any? { |topic| entry.file.include?(topic) }
      return false unless @origins.empty? || @origins.include?(entry.origin)
      return false unless @sections.empty? || @sections.include?(entry.section)
      return false unless @roles.empty? || @roles.any? { |role| entry.roles.include?(role) }

      unless @chapters.empty?
        found = entry.chapters
        return false unless @chapters.any? { |chapter| found.include?(chapter) }
      end

      @patterns.all? { |pattern| pattern.match?(entry.text) }
    end
  end

  # `docs/work/<delivery>/phaseN[/phaseNx]/*.md` -- a phase's design, plan and
  # checklist. Collecting the requirement IDs they cite turns "what did phase 5a
  # depend on" into one query instead of three document reads.
  class PhaseDocs
    SPEC = /\A(\d+)([a-z])?\z/i

    Document = Struct.new(:path, :relative, :reqs)

    def initialize(paths, prefixes)
      @paths = paths
      @prefixes = prefixes
    end

    def self.normalize(spec)
      match = SPEC.match(spec.to_s.strip.downcase.delete_prefix("phase"))
      raise UsageError, "unknown phase '#{spec}'; expected a phase like 5 or 5a" unless match

      "#{match[1]}#{match[2]}"
    end

    def find(spec)
      phase = self.class.normalize(spec)
      globs(phase).flat_map { |glob| Dir.glob(glob) }.uniq.sort.map do |path|
        Document.new(path, @paths.relative(path), Ids.extract(File.read(path, encoding: "UTF-8"), @prefixes))
      end
    end

    def globs(phase)
      match = SPEC.match(phase)
      number = match[1]
      letter = match[2]
      work = @paths.work_dir
      if letter
        [File.join(work, "*", "phase#{number}", "phase#{number}#{letter}", "*.md"),
         File.join(work, "*", "phase#{number}#{letter}", "*.md")]
      else
        [File.join(work, "*", "phase#{number}", "*.md"),
         File.join(work, "*", "phase#{number}", "*", "*.md")]
      end
    end
  end

  # Everything that turns entries into text.
  class Renderer
    def initialize(corpus, appendix, paths)
      @corpus = corpus
      @appendix = appendix
      @paths = paths
    end

    def entries(results, brief:, query:)
      out = []
      results.each do |entry|
        out << "#{entry.location} (#{entry.section})#{entry.key ? " #{entry.key}" : ""}#{tags_of(entry)}"
        out << "- #{entry.text}"
        out << "  #{entry.sub_line}" if !brief && entry.sub_line
        out << ""
      end

      files = results.map { |entry| entry.location.split(":").first }.uniq
      notes = results.count(&:note?)
      summary = "#{plural(results.size, "entry", "entries")} across #{plural(files.size, "topic file")}"
      if notes.positive?
        summary += ", #{notes} of them notes — a note states what the implementation found and " \
                   "overrides the harvested entry where it names one"
      end
      out << summary

      # The silent wrong answer this tool can give: a `--req` that "hits" but
      # whose every hit merely names the ID in a conformance-checklist sentence.
      # Exit 0 makes it look answered, so say so loudly instead.
      if results.all?(&:rollup?) && !query.reqs.empty?
        out << ""
        out << "WARNING: every result is an appendix-B conformance roll-up — it names " \
               "#{query.reqs.join(", ")} without stating the requirement. The corpus has no " \
               "substantive entry. Read the canonical text in appendix C and the owning " \
               "docs/product-spec/NN chapter instead (--prefix-info names it)."
      end
      out.join("\n")
    end

    def list_topics
      stats = {}
      @corpus.entries.each do |entry|
        row = (stats[entry.topic] ||= {entries: 0, notes: 0, ids: Set.new})
        entry.note? ? row[:notes] += 1 : row[:entries] += 1
        entry.reqs.each { |id| row[:ids] << id }
      end

      out = ["topic\tentries\tdistinct IDs\tnotes"]
      stats.keys.sort.each do |name|
        row = stats[name]
        out << "#{name}\t#{row[:entries]}\t#{row[:ids].size}\t#{row[:notes]}"
      end
      # Count only harvested topics as styleguide-derived: a note-only topic has
      # no requirement ID either, and calling it styleguide-derived is wrong.
      idless = stats.count { |_, row| row[:ids].empty? && row[:entries].positive? }
      noted = stats.count { |_, row| row[:notes].positive? }
      harvested = stats.count { |_, row| row[:entries].positive? }
      out << ""
      out << "#{stats.size} topics, #{harvested} of them harvested. #{idless} harvested topics " \
             "carry no requirement ID at all — those are styleguide-derived and are only " \
             "reachable topic-first. #{noted} topics carry a hand-written note (`--origin note`), " \
             "which states what the implementation found and overrides the harvested entry."
      out.join("\n")
    end

    def list_reqs
      index = @corpus.citation_index
      out = Ids.sort(index.keys).map do |id|
        "#{id}\t#{index[id].map(&:location).join(" ")}"
      end
      out << ""
      out << "#{index.size} requirement IDs cited across the corpus"
      out.join("\n")
    end

    def coverage
      index = @corpus.citation_index
      rows = {}
      rollup_total = 0
      @appendix.ids.each do |id|
        row = (rows[Ids.prefix_of(id)] ||= {total: 0, missing: [], rollup: []})
        row[:total] += 1
        hits = index[id]
        if hits.nil?
          row[:missing] << id
        elsif hits.all?(&:rollup?)
          # Cited, but only by a conformance-checklist sentence that names it.
          row[:rollup] << id
          rollup_total += 1
        end
      end

      out = ["requirement-ID coverage of docs/knowledge/", ""]
      out << "prefix\tsubstantive\troll-up only\tuncited\ttotal\tuncited IDs"
      rows.keys.sort.each do |prefix|
        row = rows[prefix]
        substantive = row[:total] - row[:missing].size - row[:rollup].size
        listing = row[:missing].empty? ? "-" : Ids.sort(row[:missing]).join(" ")
        out << "#{prefix}\t#{substantive}\t#{row[:rollup].size}\t#{row[:missing].size}\t#{row[:total]}\t#{listing}"
      end
      uncited = @appendix.ids.count { |id| !index.key?(id) }
      out << ""
      out << "#{@appendix.size - uncited - rollup_total}/#{@appendix.size} canonical IDs have a " \
             "substantive entry. #{rollup_total} more are named only by an appendix-B conformance " \
             "roll-up (cited, but no content). #{uncited} are cited nowhere."
      out.join("\n")
    end

    # What the corpus does NOT know about a prefix. The question a roadmap phase
    # asks before it plans anything: an ID with no substantive entry has to be
    # read out of the specification itself, and budgeting for that is the point.
    def gaps(selector)
      prefixes = if selector.strip.casecmp?("all")
                   @appendix.prefixes.to_a.sort
                 else
                   selector.split(",").map { |value| validate_prefix(value) }.uniq
                 end
      raise UsageError, "--gaps was given no prefix; pass one like --gaps HTTP, or --gaps all" if prefixes.empty?
      index = @corpus.citation_index
      out = ["knowledge gaps: canonical IDs with no substantive corpus entry", ""]
      totals = {ids: 0, rollup: 0, uncited: 0}

      prefixes.each do |prefix|
        ids = @appendix.ids_for(prefix)
        rollup = ids.select { |id| index[id]&.all?(&:rollup?) }
        uncited = ids.reject { |id| index.key?(id) }
        totals[:ids] += ids.size
        totals[:rollup] += rollup.size
        totals[:uncited] += uncited.size
        substantive = ids.size - rollup.size - uncited.size

        out << "#{prefix} — #{@appendix.subsystem_for(prefix)}"
        out << "  #{ids.size} canonical IDs: #{substantive} substantive, #{rollup.size} roll-up only, #{uncited.size} uncited"
        unless rollup.empty?
          out << "  roll-up only (named by an appendix-B conformance sentence, which states nothing):"
          out << "    #{rollup.join(" ")}"
        end
        unless uncited.empty?
          out << "  uncited (no entry in either tree names them):"
          out << "    #{uncited.join(" ")}"
        end
        chapter = @appendix.chapter_for(prefix)
        out << "  read these out of docs/product-spec/#{chapter}" if chapter && (!rollup.empty? || !uncited.empty?)
        out << ""
      end

      out << "#{totals[:rollup] + totals[:uncited]} of #{totals[:ids]} IDs in " \
             "#{plural(prefixes.size, "prefix", "prefixes")} have no substantive entry " \
             "(#{totals[:rollup]} roll-up only, #{totals[:uncited]} uncited). Those are the ones a " \
             "phase has to read out of the specification rather than out of the corpus."
      out.join("\n")
    end

    # Replaces the hand-maintained prefix -> chapter routing table: subsystem,
    # owning chapter and counts, all derived from appendix C at runtime.
    def prefix_info(selector)
      prefix = validate_prefix(selector)
      ids = @appendix.ids_for(prefix)
      levels = @appendix.levels_for(prefix).map { |level, count| "#{count} #{level}" }.join(", ")
      chapter = @appendix.chapter_for(prefix)
      index = @corpus.citation_index
      cited = ids.count { |id| index.key?(id) }
      substantive = ids.count { |id| index[id]&.any? { |entry| !entry.rollup? } }
      topics = topics_for_prefix(prefix)

      out = ["#{prefix} — #{@appendix.subsystem_for(prefix)}"]
      out << "  #{ids.size} canonical IDs (#{ids.first}..#{ids.last}), #{levels}"
      out << "  owning chapter: #{chapter ? "docs/product-spec/#{chapter}" : "not resolvable from the subsystem cell — grep docs/product-spec/"}"
      out << "  canonical text:  grep -n '^| #{ids.first} ' #{@paths.relative(@paths.appendix_c)}"
      out << "  corpus: #{substantive} of #{ids.size} IDs have a substantive entry, #{cited - substantive} are roll-up only, #{ids.size - cited} are uncited"
      out << "  topics carrying #{prefix} knowledge: #{topics.join(" ")}" unless topics.empty?
      out << "  the whole family:  --prefix #{prefix} --section rules --brief"
      out.join("\n")
    end

    def phase_header(phase, documents)
      out = ["phase #{phase}: #{plural(documents.size, "document")}", ""]
      documents.each do |document|
        listing = document.reqs.empty? ? "no requirement ID" : "#{document.reqs.size}: #{Ids.compress(document.reqs)}"
        out << "#{document.relative} — #{listing}"
      end
      ids = Ids.sort(documents.flat_map(&:reqs).uniq)
      out << ""
      out << "#{ids.size} distinct requirement IDs cited by phase #{phase}; querying the corpus for all of them."
      out.concat(["", ""])
      out.join("\n")
    end

    def no_phase_docs(phase)
      "no phase documents found for phase #{phase}. Looked under " \
        "#{@paths.relative(@paths.work_dir)}/*/phase#{phase}/. A phase gets its documents when it " \
        "is planned, so nothing here means the phase has not been written yet — there is no " \
        "requirement-ID set to query. Use --prefix-info and --gaps to scope it from appendix C " \
        "instead."
    end

    # A zero-result query must never look like "the corpus has nothing to say"
    # when it is really a typo, the wrong topic name, or two filters that cannot
    # both hold. Spend the tokens on saying which of those it was.
    #
    # The dimension a hint blames has to be the dimension that emptied the
    # result. A per-filter hint that fires unconditionally states falsehoods:
    # with `--prefix HTTP --req PAGE-11` it would report "PAGE-11 is canonical
    # but no entry cites it yet", which is wrong -- entries cite it, none of them
    # an HTTP one. So each dimension is first tested alone, and only a dimension
    # that matches nothing on its own gets to explain itself.
    def no_matches(query)
      out = ["no matching entries."]
      used = query.used_dimensions
      barren = used.reject { |name| @corpus.entries.any? { |entry| query.solo(name).match?(entry) } }

      if barren.empty?
        alone = used.map do |name|
          "#{name} #{@corpus.entries.count { |entry| query.solo(name).match?(entry) }}"
        end
        out << "  every filter matches something on its own; no entry satisfies all of them at " \
               "once (matching alone: #{alone.join(", ")}). Filters AND together — drop one."
        return out.join("\n")
      end

      barren.each { |name| out.concat(hint_for(name, query)) }
      out.join("\n")
    end

    private

    def validate_prefix(selector)
      prefix = selector.to_s.strip.upcase
      unless @appendix.prefixes.include?(prefix)
        raise UsageError, "'#{prefix}' is not a requirement-ID prefix in appendix C. The prefixes " \
                          "are #{@appendix.prefixes.to_a.sort.join(" ")}"
      end
      prefix
    end

    # The tags an entry can carry, in the order that matters to a reader: an
    # override first, because it changes whether the entry is still true.
    def tags_of(entry)
      tags = entry.overridden_by.map { |at| " [overridden by #{at}]" }
      tags << " [appendix-B roll-up]" if entry.rollup?
      tags.join
    end

    def plural(count, singular, plural_form = "#{singular}s")
      "#{count} #{count == 1 ? singular : plural_form}"
    end

    def topics_for_prefix(prefix)
      counts = Hash.new(0)
      @corpus.entries.each do |entry|
        entry.reqs.each { |id| counts[entry.topic] += 1 if Ids.prefix_of(id) == prefix }
      end
      counts.sort_by { |topic, count| [-count, topic] }.first(3).map(&:first)
    end

    def hint_for(dimension, query)
      case dimension
      when :reqs then hint_for_reqs(query)
      when :keys then hint_for_keys(query)
      when :prefixes then query.prefixes.map { |prefix| "  no entry cites any #{prefix} ID." }
      when :origins then hint_for_origins(query)
      when :topics then hint_for_topics(query)
      when :roles then hint_for_roles(query)
      when :sections then hint_for_sections(query)
      when :chapters then hint_for_chapters(query)
      else ["  text filters are applied to entry text only; try --grep with a looser pattern, " \
            "or fewer bare words."]
      end
    end

    def hint_for_reqs(query)
      index = @corpus.citation_index
      out = []
      query.reqs.each do |id|
        prefix = Ids.prefix_of(id)
        number = Ids.number_of(id)
        out << if @appendix.key?(id)
                 "  #{id} is canonical but no entry cites it yet."
               else
                 "  #{id} is not a canonical requirement ID (not in appendix C)."
               end
        # Never offer the queried ID back as its own nearest neighbour.
        nearest = index.keys
          .select { |other| other != id && Ids.prefix_of(other) == prefix }
          .sort_by { |other| [(Ids.number_of(other) - number).abs, Ids.number_of(other)] }
          .first(5)
        out << if nearest.empty?
                 cited = index.keys.map { |other| Ids.prefix_of(other) }.uniq.sort
                 "  no #{prefix} ID is cited anywhere. cited prefixes: #{cited.join(" ")}"
               else
                 "  nearest cited #{prefix} IDs: #{nearest.join(" ")}"
               end
        topics = topics_for_prefix(prefix)
        out << "  topics carrying #{prefix} knowledge: #{topics.join(" ")}" unless topics.empty?
      end
      out
    end

    # A key that resolves to nothing is not a typo, it is news: the entry it
    # named has been reworded, so whatever cites it -- a note, an audit -- is
    # describing a rule that no longer exists in that form.
    def hint_for_keys(query)
      query.keys.map do |key|
        topic = key.split("/").first
        cited_by = @corpus.entries.select { |entry| entry.text.include?("`#{key}`") }.map(&:location)
        known = @corpus.entries.any? { |entry| entry.topic == topic }
        next "  no entry carries the key #{key}, and no topic '#{topic}' exists." unless known

        where = cited_by.empty? ? "" : " It is cited by #{cited_by.join(" ")}, which needs updating."
        "  no entry carries the key #{key}. A key digests the entry's text, so a reworded or " \
          "re-harvested rule gets a new one.#{where}"
      end
    end

    def hint_for_origins(query)
      query.origins.map do |origin|
        if origin == "note"
          "  the notes tree carries only what an implementation found that overrides a harvested " \
            "rule; it is meant to be small."
        else
          "  no harvested entry matches. harvested/ is the whole corpus bar the notes, so this is " \
            "a filter combination, not an empty tree."
        end
      end
    end

    def hint_for_topics(query)
      known = @corpus.topics
      query.topics.map { |topic| "  no topic file matches '#{topic}'. available: #{known.join(" ")}" }
    end

    def hint_for_roles(query)
      query.roles.map do |role|
        if role == "review"
          "  no review-role entry matches. review is the notes tree's role; under harvested/ it " \
            "is a structural violation, so there are none."
        else
          "  no entry carries the role #{role}."
        end
      end
    end

    def hint_for_sections(query)
      query.sections.map do |section|
        tail = section == "Superseded" ? " — it exists only under notes/, where an override is recorded." : "."
        "  the #{section} section holds no entry in either tree#{tail}"
      end
    end

    def hint_for_chapters(query)
      known = @corpus.entries.flat_map(&:chapters).uniq.sort_by(&:to_i)
      query.chapters.map do |chapter|
        "  no entry cites styleguide chapter #{chapter}. harvested chapters: #{known.join(" ")}"
      end
    end
  end

  USAGE = <<~TEXT
    Usage: scripts/knowledge.rb [options] [words...]

    Query docs/knowledge/ — both harvested/ (what the documents say) and notes/
    (what the implementation found; it overrides). Different filters AND together;
    values within one filter OR.

      --req <ID>          entries citing that requirement ID (repeatable, comma-ok).
                          Comma form is the whole-task query: --req HTTP-13,HTTP-14
      --key <topic/hex>   the one entry with that key — how a note's citation is
                          resolved. An unknown key is reported, not an error: it
                          means the entry was reworded and the citation is stale.
      --prefix <name>     a whole ID family: --prefix HTTP. The audit-scale filter.
      --origin <names>    #{ORIGINS.join(" | ")}
      --topic <names>     topic files whose name contains any of these (substring)
      --section <names>   #{SECTIONS.map(&:downcase).join(" | ")}
      --role <names>      #{ROLES.join(" | ")}
      --chapter <n>       styleguide chapter, e.g. 6 (a "6.7" drops the .7)
      --grep <regex>      case-insensitive regex over entry text (repeatable)
      <words...>          bare words: case-insensitive substrings, all must match
      --phase <N[x]>      every requirement ID cited by docs/work/*/phaseN[/phaseNx]/,
                          queried as one --req set, with the per-document breakdown
      --brief             drop <sub> provenance lines (~30% less output)
      --json              machine-readable records
      --list-topics       every topic with entry, distinct-ID and note counts
      --list-reqs         requirement-ID -> location map (large; prefer --coverage)
      --coverage          substantive vs roll-up-only vs uncited, per prefix
      --gaps <NAMES|all>  the IDs with no substantive entry, roll-up-only and
                          uncited listed apart (comma-ok: --gaps HTTP,PAGE). What a
                          phase must read out of the spec rather than the corpus.
      --prefix-info <P>   subsystem, owning chapter and ID count for a prefix, all
                          derived from appendix C — no routing table to go stale
      --no-drift-check    skip the stale-source warning (it hashes touched sources)
      --root <dir>        repository root (default: the parent of scripts/;
                          #{Paths::ENV_ROOT} overrides that)
      --help

    Every result carries a stable key, <topic>/<8 hex>, digested from the entry
    text. Name a rule by that key in a note: it survives a re-order, and it changes
    exactly when the rule's text does — including on a re-harvest that rewords it,
    which is when the note needs revisiting. Resolve one with --key. A harvested
    entry a note overrides prints [overridden by notes/...].

    An unknown --role, --section, --chapter, --origin, --prefix or --gaps exits 2:
    a typo there is a silent empty result. An unknown --req only warns, because a
    not-yet-canonical ID is a legitimate thing to ask about.

    Exits 1 when a query matches nothing, and when the corpus has not been
    harvested in this checkout at all.

    Examples:
      scripts/knowledge.rb --req HTTP-13,HTTP-14,HTTP-15   # one task's whole ID set
      scripts/knowledge.rb --origin note --brief           # start of a phase: what we found
      scripts/knowledge.rb --prefix HTTP --section rules   # an audit group, by ID family
      scripts/knowledge.rb --chapter 6 attr keyword        # "styleguide 6.7"
      scripts/knowledge.rb --prefix-info RETRY             # subsystem, chapter, counts
      scripts/knowledge.rb --gaps RETRY,RECOV              # what the corpus does NOT know
      scripts/knowledge.rb --phase 5a --brief              # a past phase's whole ID set
  TEXT

  # Argument parsing and dispatch. Takes its streams so the tests can drive it in
  # process and read what it wrote.
  class CLI
    def initialize(stdout: $stdout, stderr: $stderr)
      @stdout = stdout
      @stderr = stderr
    end

    def run(argv)
      options, words = parse(argv)
      if options[:help]
        @stdout.print(USAGE)
        return 0
      end
      dispatch(options, words)
    rescue UsageError, OptionParser::ParseError => error
      @stderr.puts(error.message)
      2
    rescue NotHarvested => error
      @stderr.puts(error.message)
      1
    end

    private

    def parse(argv)
      options = {req: [], key: [], prefix: [], origin: [], topic: [], section: [],
                 role: [], chapter: [], grep: [], drift_check: true}
      parser = OptionParser.new do |opts|
        opts.on("--req VALUE") { |value| options[:req] << value }
        opts.on("--key VALUE") { |value| options[:key] << value }
        opts.on("--prefix VALUE") { |value| options[:prefix] << value }
        opts.on("--origin VALUE") { |value| options[:origin] << value }
        opts.on("--topic VALUE") { |value| options[:topic] << value }
        opts.on("--section VALUE") { |value| options[:section] << value }
        opts.on("--role VALUE") { |value| options[:role] << value }
        opts.on("--chapter VALUE") { |value| options[:chapter] << value }
        opts.on("--grep VALUE") { |value| options[:grep] << value }
        opts.on("--phase VALUE") { |value| options[:phase] = value }
        opts.on("--gaps VALUE") { |value| options[:gaps] = value }
        opts.on("--prefix-info VALUE") { |value| options[:prefix_info] = value }
        opts.on("--root VALUE") { |value| options[:root] = value }
        opts.on("--brief") { options[:brief] = true }
        opts.on("--json") { options[:json] = true }
        opts.on("--list-topics") { options[:list_topics] = true }
        opts.on("--list-reqs") { options[:list_reqs] = true }
        opts.on("--coverage") { options[:coverage] = true }
        opts.on("--no-drift-check") { options[:drift_check] = false }
        opts.on("-h", "--help") { options[:help] = true }
      end
      words = parser.parse(argv)
      [options, words]
    end

    def dispatch(options, words)
      paths = options[:root] ? Paths.new(options[:root]) : Paths.default
      appendix = AppendixC.load(paths)
      # --gaps and --prefix-info answer from appendix C alone, so they are the
      # two commands worth running before anything has been harvested.
      tolerant = !(options[:gaps] || options[:prefix_info]).nil?
      corpus = load_corpus(paths, appendix.prefixes, tolerant: tolerant)
      renderer = Renderer.new(corpus, appendix, paths)

      return emit(renderer.prefix_info(options[:prefix_info])) if options[:prefix_info]
      return emit(renderer.gaps(options[:gaps])) if options[:gaps]
      return emit(renderer.list_topics) if options[:list_topics]
      return emit(renderer.list_reqs) if options[:list_reqs]
      return emit(renderer.coverage) if options[:coverage]

      query_command(options, words, paths, appendix, corpus, renderer)
    end

    def emit(text)
      @stdout.puts(text)
      0
    end

    def load_corpus(paths, prefixes, tolerant:)
      Corpus.load(paths, prefixes)
    rescue NotHarvested => error
      raise unless tolerant

      @stderr.puts("note: #{error.message.lines.first.strip} — reporting against appendix C alone.")
      Corpus.new([])
    end

    def query_command(options, words, paths, appendix, corpus, renderer)
      extra_reqs = []
      if options[:phase]
        documents = PhaseDocs.new(paths, appendix.prefixes).find(options[:phase])
        phase = PhaseDocs.normalize(options[:phase])
        return emit(renderer.no_phase_docs(phase)) if documents.empty?

        @stdout.puts(renderer.phase_header(phase, documents))
        extra_reqs = documents.flat_map(&:reqs).uniq
        return 0 if extra_reqs.empty?
      end

      query = Query.build(options, words, appendix, extra_reqs: extra_reqs, warn: @stderr)
      if query.empty?
        @stdout.print(USAGE)
        return 0
      end

      results = corpus.entries.select { |entry| query.match?(entry) }
      warn_about_drift(results, paths) if options[:drift_check]

      if options[:json]
        @stdout.puts(JSON.pretty_generate(results.map(&:to_h)))
        return results.empty? ? 1 : 0
      end
      if results.empty?
        @stdout.puts(renderer.no_matches(query))
        return 1
      end
      emit(renderer.entries(results, brief: options[:brief], query: query))
    end

    def warn_about_drift(results, paths)
      return if results.empty?

      check = DriftCheck.for(paths)
      check&.warnings_for(results)&.each { |warning| @stderr.puts(warning) }
    end
  end
end

exit(Knowledge::CLI.new.run(ARGV)) if $PROGRAM_NAME == __FILE__
