#!/usr/bin/env ruby
# frozen_string_literal: true
#
# SPDX-License-Identifier: MIT
# scripts/verify_knowledge_structure.rb
#
# `docs/knowledge/` is two trees, and this is the gate that keeps them apart.
#
#   harvested/  what the source documents say. Generated by `knowledge-harvest`,
#               never hand-edited.
#   notes/      what the implementation found. Hand-written, role `review`, a
#               manual `sha:` marker, and it outranks the harvested entry it
#               names.
#
# Why a gate rather than a convention: a `<sub>` sha digests the WHOLE source
# file, not the entry, so every entry harvested from one file carries the same
# value and an edit to an entry's text does not change it. The next harvest
# cannot see the edit — it regenerates the original text or writes a duplicate.
# Hand-written knowledge under `harvested/` is therefore not just untidy, it is
# scheduled for silent deletion. The rules below are the smallest set that
# catches it, and none of them needs a file outside the repository.
#
# Structural only. It says nothing about whether an entry is TRUE — that is what
# `knowledge_drift.rb` and a re-harvest are for.
#
# Exit 0 clean, 1 with violations, 2 when the gate itself cannot run.

require "optparse"
require "set"
require_relative "knowledge"

module Knowledge
  # The structural rules, and the parse-hole floor that keeps them from passing
  # vacuously over an empty tree.
  class StructureGate
    # A `<sub>` source is `path/to/file.md:12-18`, `…:12`, or a bare path.
    LINE_SUFFIX = /:[\d,\-]+\z/
    # `| topic | `file.md` | 42 | roles | conflicts | date |` in INDEX.md.
    INDEX_ROW = /\A\|\s*([a-z0-9-]+)\s*\|\s*`([^`]+)`\s*\|\s*(\d+)\s*\|/
    # A generated INDEX that a hand edit has drifted below is a stale index, not
    # a parse hole; only a collapse this large means the parser stopped working.
    PARSE_FLOOR_RATIO = 0.5

    def initialize(paths, stdout: $stdout, stderr: $stderr)
      @paths = paths
      @stdout = stdout
      @stderr = stderr
    end

    def run
      return no_corpus unless Dir.exist?(@paths.knowledge_dir)

      manifest = SourceManifest.load(@paths)
      roots = source_roots(manifest)
      corpus = Corpus.load(@paths, AppendixC.load(@paths).prefixes)
      harvested = corpus.entries.reject(&:note?)
      check_parse_floor(harvested)

      violations = structural_violations(harvested, roots) +
                   orphaned_note_keys(corpus.entries) +
                   note_violations(corpus.entries) +
                   stray_topic_files

      return report(violations) unless violations.empty?

      notes = corpus.entries.size - harvested.size
      @stdout.puts("knowledge structure OK: #{harvested.size} harvested entries, each with a " \
                   "source under one of #{roots.size} roots and a role among " \
                   "#{HARVESTED_ROLES.join("/")}, none Superseded; #{notes} notes, all " \
                   "review-role, every cited key live; nothing stranded at the root.")
      0
    end

    private

    # An unharvested checkout is a legitimate state, not a violation: this gate
    # protects a corpus that exists.
    def no_corpus
      @stdout.puts("knowledge structure OK: #{@paths.relative(@paths.knowledge_dir)} does not " \
                   "exist under #{@paths.root}, so there are no two trees to keep apart yet.")
      0
    end

    def report(violations)
      violations.each { |violation| @stderr.puts("knowledge-structure violation: #{violation}") }
      @stderr.puts("#{violations.size} violation(s). docs/knowledge/harvested/ carries only " \
                   "harvested entries; hand-written knowledge lives in docs/knowledge/notes/ " \
                   "with role `review` and a manual sha marker.")
      1
    end

    # The source roots are not hardcoded: they are the directories the harvest
    # manifest itself names. One of them is an absolute path on the harvest
    # machine (the styleguide is a sibling repository), so hardcoding it would
    # make this gate machine-specific — and deriving it means a fourth root is a
    # SOURCES.md edit, reviewable in the same diff as the entries that use it.
    def source_roots(manifest)
      roots = manifest.roots
      # One row at a root's parent would widen the allowlist to everything
      # beneath it — a row naming a file at the `docs/` root makes `docs` a root,
      # and then every `docs/work/...` citation passes. Refuse rather than
      # silently widen.
      roots.each do |root|
        swallowed = roots.find { |other| other != root && other.start_with?("#{root}/") }
        next if swallowed.nil?

        raise UsageError, "#{manifest.path} derives the source root '#{root}', which contains " \
                          "'#{swallowed}'. A root that contains another admits everything " \
                          "beneath it; list sources at one level, not two."
      end
      roots
    end

    # A parse that silently yields nothing (a CRLF topic file, a moved
    # directory) would let this gate print OK over an empty tree, which is worse
    # than failing. The Node original pinned an absolute floor; here the floor is
    # derived from the generated INDEX.md, so it calibrates itself as the corpus
    # grows from zero rather than needing a magic number maintained by hand.
    def check_parse_floor(harvested)
      counts = Hash.new(0)
      harvested.each { |entry| counts[entry.topic] += 1 }
      stated = index_counts
      return check_uncounted_floor(counts) if stated.empty?

      empty = stated.select { |topic, count| count.positive? && counts[topic].zero? }
      unless empty.empty?
        raise UsageError, "#{@paths.relative(@paths.topic_index)} states entries for " \
                          "#{empty.keys.sort.join(", ")}, and each parses to zero. The corpus did " \
                          "not shrink by hand — a parse is failing (a CRLF or BOM topic file, a " \
                          "moved directory), and every rule below would pass vacuously over the hole."
      end

      total = counts.values.sum
      floor = (stated.values.sum * PARSE_FLOOR_RATIO).floor
      return if total >= floor

      raise UsageError, "only #{total} harvested entries parsed against the #{stated.values.sum} " \
                        "#{@paths.relative(@paths.topic_index)} states; below the #{floor} floor " \
                        "that separates an edit from a broken parse."
    end

    # Without a generated index, the tell is a topic file that plainly holds
    # bullets and yields no entry.
    def check_uncounted_floor(counts)
      broken = Corpus.topic_files(@paths).select do |topic|
        next false unless topic[:origin] == "harvested"
        next false unless counts[topic[:topic]].zero?

        File.foreach(topic[:path]).any? { |line| line.start_with?("- ") }
      end
      return if broken.empty?

      raise UsageError, "#{broken.map { |topic| topic[:file] }.join(", ")} hold bullets but parse " \
                        "to zero entries; the parser is failing on them and every rule below would " \
                        "pass vacuously over the hole."
    end

    def index_counts
      return {} unless File.file?(@paths.topic_index)

      counts = {}
      File.foreach(@paths.topic_index) do |line|
        match = INDEX_ROW.match(line)
        counts[match[1]] = match[3].to_i if match
      end
      counts
    end

    # `normalize` first: a `..` segment makes a string prefix test meaningless,
    # and the point of this check is where the path actually lands.
    def under_root?(source, roots)
      path = File.expand_path(source.sub(LINE_SUFFIX, ""), "/")
      roots.any? { |root| path.start_with?("#{File.expand_path(root, "/")}/") }
    end

    def structural_violations(harvested, roots)
      violations = []
      harvested.each do |entry|
        at = "#{entry.location} (#{entry.section})"

        if entry.roles.include?("review")
          violations << "#{at}: role `review` under harvested/. A review-role entry is " \
                        "hand-written knowledge; move it to docs/knowledge/notes/."
        end
        # `review` is the label an honest hand edit wears. An invented role is
        # what a careless one wears, and it would otherwise pass every rule here.
        entry.roles.each do |role|
          next if role == "review" || HARVESTED_ROLES.include?(role)

          violations << "#{at}: role `#{role}` under harvested/, which is not one of " \
                        "#{HARVESTED_ROLES.join(", ")}. A harvested entry carries the role of the " \
                        "document it came from."
        end
        # The per-source loop below iterates zero times on an entry with no
        # provenance line at all, so the strongest rule here would never run on
        # the one shape a hand-written bullet is most likely to have.
        if entry.sources.empty?
          violations << "#{at}: no source. Every harvested entry carries a `<sub>` naming the " \
                        "document it came from; a bullet without one was written by hand."
        end
        if entry.section == "Superseded"
          violations << "#{at}: a Superseded entry under harvested/. Superseding is a judgement " \
                        "the implementation made; it belongs in docs/knowledge/notes/."
        end
        entry.sources.each do |source|
          next if under_root?(source, roots)

          violations << "#{at}: cites `#{source}`, which is under none of the harvested source " \
                        "roots (#{roots.join(", ")}). Only a harvest of those roots belongs in " \
                        "harvested/."
        end
      end
      violations
    end

    # A note names the harvested rule it overrides by that rule's stable key,
    # which is digested from the entry's text — so a re-harvest that rewords the
    # rule changes its key and silently orphans every note citing it. Failing
    # here means a re-harvest cannot land until the notes it invalidates are
    # updated in the same commit, which is the point.
    def orphaned_note_keys(entries)
      live = entries.reject(&:note?).map(&:key).to_set
      violations = []
      entries.each do |entry|
        next unless entry.note?

        entry.text.scan(Corpus::CITED_KEY) do |(key)|
          next if live.include?(key)

          violations << "#{entry.location}: cites `#{key}`, which no harvested entry carries. A " \
                        "key is digested from the entry text, so a re-harvest that rewords the " \
                        "rule changes it — update the note to the new key " \
                        "(`scripts/knowledge.rb --topic <topic> --section <section>` prints it)."
        end
      end
      violations
    end

    # The mirror of the first rule, and fatal for the same reason rather than
    # advisory: a note that does not say `review` reads, in a query result,
    # exactly as though a source document had said it.
    def note_violations(entries)
      entries.select { |entry| entry.note? && !entry.roles.include?("review") }.map do |entry|
        "#{entry.location}: a note whose role is `#{entry.role || "none"}`, not `review`. A note " \
          "states what the implementation found; that is what the role says."
      end
    end

    # A rule beyond the ones the trees themselves imply, because the accident it
    # catches is silent: `knowledge-harvest` defaults its `--corpus` to
    # `<cwd>/docs/knowledge/`, so a run that forgets
    # `--corpus docs/knowledge/harvested` writes a third copy of the corpus at
    # the root. No query reads it — the CLI walks harvested/ and notes/ — so the
    # knowledge is not wrong, it is invisible.
    def stray_topic_files
      Dir.children(@paths.knowledge_dir)
        .select { |name| name.end_with?(".md") && name != "README.md" }
        .select { |name| File.file?(File.join(@paths.knowledge_dir, name)) }
        .sort
        .map do |name|
          "docs/knowledge/#{name}: a topic file at the root of docs/knowledge/, which is neither " \
            "tree — no query reads it. Move it into harvested/ or notes/. (A `knowledge-harvest` " \
            "run without `--corpus docs/knowledge/harvested` writes here.)"
        end
    end
  end
end

if $PROGRAM_NAME == __FILE__
  root = nil
  begin
    OptionParser.new do |opts|
      opts.banner = "Usage: scripts/verify_knowledge_structure.rb [options]"
      opts.separator ""
      opts.separator "Checks that docs/knowledge/harvested/ (generated) and docs/knowledge/notes/"
      opts.separator "(hand-written) keep to their structural rules, so a hand-written entry is"
      opts.separator "never mistaken for a generated one. Exits 0 clean, 1 with violations, 2 when"
      opts.separator "the gate itself cannot run."
      opts.separator ""
      opts.on("--root VALUE", "repository root (default: the parent of scripts/)") { |value| root = value }
      opts.on("-h", "--help", "print this message") do
        puts opts
        exit 0
      end
    end.parse!(ARGV)
    paths = root ? Knowledge::Paths.new(root) : Knowledge::Paths.default
    exit(Knowledge::StructureGate.new(paths).run)
  rescue Knowledge::UsageError, Knowledge::NotHarvested, OptionParser::ParseError => error
    warn(error.message)
    exit 2
  end
end
