# frozen_string_literal: true
# SPDX-License-Identifier: MIT

# Generates gems/dexpace-conformance/lib/dexpace/conformance/levels.rb from appendix C.
#
# Appendix C is normative and FROZEN (CLAUDE.md; Guard::FROZEN). This tool READS it and writes
# exactly one file, TARGET, which is not under docs/. There is no code path that writes SOURCE.
#
# A gem cannot read docs/ from a consumer's machine, so the map is committed inside the gem and
# test/gates/requirement_levels_test.rb regenerates it in memory and diffs it against the
# committed file -- the way the runtime surface snapshot is kept honest. `MUST NOT` maps to
# :must: it is a MUST with a negated predicate, and appendix C holds exactly one.
#
#   ruby tools/requirement_levels.rb          # regenerate levels.rb
#   ruby tools/requirement_levels.rb --check  # exit 1 if levels.rb is stale
require "pathname"

# The appendix-C parser and the levels.rb renderer.
module RequirementLevels
  ROOT = Pathname(__dir__).join("..").expand_path
  SOURCE = ROOT.join("docs/product-spec/appendix-c-consolidated-normative-requirement-index.md")
  TARGET = ROOT.join("gems/dexpace-conformance/lib/dexpace/conformance/levels.rb")
  # CLAUDE.md's 19 prefixes, in appendix-C order. Restricting the regex is what keeps ISO-8601 and
  # RFC-shaped tokens out of the map.
  PREFIXES = %w[SEAM HTTP IO BODY CTX PIPE RECOV RETRY REDIR AUTH PAGE SSE SERDE OBS CFG
                TRANSPORT ASYNC XCUT NFR].freeze
  ROW = /\A\| ((?:#{PREFIXES.join("|")})-\d+) \| (MUST NOT|MUST|SHOULD|MAY) \|/
  LEVEL = { "MUST" => :must, "MUST NOT" => :must, "SHOULD" => :should, "MAY" => :may }.freeze

  extend self

  # @param source [Pathname] appendix C
  # @return [Hash{String => Symbol}] every requirement ID's normative level
  def parse(source = SOURCE)
    source.each_line.filter_map { |line| (m = ROW.match(line)) && [m[1], LEVEL.fetch(m[2])] }.to_h
  end

  # @param map [Hash{String => Symbol}]
  # @return [String] the whole of levels.rb
  def render(map)
    rows = map.map { |id, level| "        #{id.inspect} => #{level.inspect}," }.join("\n")
    <<~RUBY
      # frozen_string_literal: true
      # SPDX-License-Identifier: MIT

      # GENERATED by tools/requirement_levels.rb from appendix C -- do not edit; re-run the tool.
      module Dexpace
        module Conformance
          # The normative level of every requirement ID, so a Report can tell a MUST-level vacuity
          # from a SHOULD-level one (design R3; NFR-17). A gem cannot read docs/ at runtime, so the
          # map is committed here and test/gates/requirement_levels_test.rb diffs it against
          # appendix C on every run. `MUST NOT` is :must -- a MUST with a negated predicate.
          #
          # rubocop:disable Metrics/ModuleLength, Metrics/CollectionLiteralLength -- a generated
          # table of every requirement ID in the specification: the size IS the specification's,
          # and "read the data from an external source" is what a gem cannot do, since docs/ is
          # not on a consumer's machine.
          module Levels
            # Every requirement ID in appendix C mapped to its RFC 2119 level.
            OF = {
      #{rows}
            }.freeze

            # @param id [String] a requirement ID
            # @return [Boolean] true when appendix C holds it
            def self.known?(id) = OF.key?(id)

            # @param id [String] a requirement ID
            # @return [Symbol] :must, :should, :may, or :unknown for an ID appendix C does not hold
            def self.of(id) = OF.fetch(id, :unknown)

            # @param id [String] a requirement ID
            # @return [Boolean] true only for a MUST or a MUST NOT
            def self.must?(id) = of(id) == :must
          end
          # rubocop:enable Metrics/ModuleLength, Metrics/CollectionLiteralLength
        end
      end
    RUBY
  end
end

if $PROGRAM_NAME == __FILE__
  rendered = RequirementLevels.render(RequirementLevels.parse)
  if ARGV.include?("--check")
    # The optional path is what lets the gate's own test drive the FAILING case: with TARGET fixed
    # the test could only ever assert exit 0, and a --check that always exited 0 would pass it --
    # measured, by mutation, during this phase. `--check <path>` compares the same render against
    # a file the test wrote, so both exits are covered.
    target = Pathname((ARGV - ["--check"]).first || RequirementLevels::TARGET)
    exit(target.exist? && target.read == rendered ? 0 : 1)
  else
    RequirementLevels::TARGET.write(rendered)
    puts "wrote #{RequirementLevels::TARGET} (#{RequirementLevels.parse.size} ids)"
  end
end
