# SPDX-License-Identifier: MIT

module Dexpace
  interface _Builder[T]
    def build: () -> T
  end

  module Builder
    def self.build_all: (Array[Builder] builders) -> Array[untyped]

    def build: () -> untyped
  end
end
